openapi: 3.1.0
info:
  title: API сервер для демо-проекта «Шесть городов».
  description: |-
    * Список ресурсов и маршрутов сервера «Шесть городов».
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0
tags:
  - name: users
    description: Действия с пользователем.
  - name: offers
    description: Действия с объявлениями.
  - name: comments
    description: Действия с комментариями.

paths:
  /offers:
    get:
      tags:
        - offers
      summary: Получение списка предложений по аренде
      description: Получение списка предложений по аренде
      parameters:
        - in: query
          name: city
          schema:
            $ref: '#/components/schemas/city'
        - in: query
          name: limit
          schema:
            type: integer
            example: 10

      responses:
        '200':
          description: Получение Получение списка предложений по аренде. Объект предложения.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/offer'

    post:
      tags:
        - offers
      summary: Создание нового предложения
      description: Создает новое предложение
      requestBody:
        description: Информация для создания нового предложения.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createOffer'
        required: true

      responses:
        '201':
          description: Создано новое предложение. Объект предложения.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offer'

        '500':
          description: Internal server error.

  /offers/premium:
    get:
      tags:
        - offers
      summary: Получение списка премиальных предложений по аренде
      parameters:
        - in: query
          name: city
          required: true
          schema:
            $ref: '#/components/schemas/city'
        - in: query
          name: limit
          schema:
            type: integer
            example: 10

      responses:
        '200':
          description: Получение Получение списка премиальных предложений по аренде. Объект предложения.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/offer'

  /offers/{offerId}:
    parameters:
      - $ref: '#/components/parameters/offerId'
    get:
      tags:
        - offers
      summary: Получение детальной информация по предложению
      description: Получение детальной информация по предложению, все поля offer
      responses:
        '200':
          description: Получение детальной информация по предложению. Объект предложения.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offer'

        '404':
          description: Данного предложения не существует.

    delete:
      tags:
        - offers
      summary: Удаление предложения
      responses:
        '204':
          description: Удалено

    patch:
      tags:
        - offers
      summary: Обновление предложения

      requestBody:
        description: Информация для обновления предложения.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateOffer'
        required: true

      responses:
        '200':
          description: Предложение обновлено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offer'

  /offers/{offerId}/comments:
    parameters:
      - $ref: '#/components/parameters/offerId'
    get:
      tags:
        - comments
      summary: Получить комментарии к предложению
      responses:
        '200':
          description: Список комментариев
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/comment'

    post:
      tags:
        - comments
      summary: Создать комментарий к предложению
      requestBody:
        description: Информация для создания нового комментария.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createComment'
        required: true

      responses:
        '201':
          description: Комментарий создан. Объект комментария.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comment'

  /offers/{offerId}/favorites:
    parameters:
      - $ref: '#/components/parameters/offerId'
    post:
      tags:
        - offers
      summary: Добавить объявление в избранное
      description: Добавляет объявление пользователя в список избранного.
      responses:
        '201':
          description: Объявление добавлено в избранное
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offer'
        '400':
          description: Невальдный ID у объявления
        '401':
          description: Пользователь не авторизован
        '404':
          description: Объявление с указанным ID не найдено

    delete:
      tags:
        - offers
      summary: Удалить объявление из избранного
      description: Удаляет объявление пользователя из списка избранного.
      responses:
        '204':
          description: Объявление удалено из избранного
        '400':
          description: Невальдный ID у объявления
        '401':
          description: Пользователь не авторизован
        '404':
          description: Объявление с указанным ID не найдено

  /register:
    post:
      tags:
        - users
      summary: Регистрация пользователя
      description: Регистрирует нового пользователя.

      requestBody:
        description: Информация для создания нового пользователя.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createUser'
        required: true

      responses:
        '201':
          description: Пользователь зарегистрирован. Объект пользователя.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createUserRDO'

        '409':
          description: Пользователь с таким email уже существует.

  /login:
    post:
      tags:
        - users
      summary: Авторизация пользователя
      description: Авторизует пользователя на основе логина и пароля

      responses:
        '200':
          description: Пользователь авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/loggedUser'

        '404':
          description: Пользователь не найден.

        '401':
          description: Email или password не верны.

  /users/{userId}/avatar:
    parameters:
      - $ref: '#/components/parameters/userId'
    post:
      tags:
        - users
      summary: Загрузить изображение аватара
      description: Загружает изображение аватара пользователя. Изображение
        аватара должно быть в формате `png` или `jpg`.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  format: binary
      responses:
        '201':
          description: Аватар успешно загружен
          content:
            application/json:
              schema:
                type: object
                properties:
                  avatar:
                    type: string
                    format: uri
                    example: /uploads/avatars/6329c3d6a04ab1061c6425ea.png
        '400':
          description: Невалидный id или нет файла | Количество файлов больше чем 1 | Изображение пользователя не в формате .jpg или .png;
        '401':
          description: Пользователь не авторизован

  /logout:
    post:
      tags:
        - users
      summary: Выход пользователя
      description: Логаут авторизованного пользователя
      responses:
        '204':
          description: Пользователь вышел

components:
  schemas:
    city:
      type: string
      enum: [Paris, Cologne, Brussels, Amsterdam, Hamburg, Dusseldorf]

    propertyType:
      type: string
      enum: [apartment, house, room, hotel]

    propertyFeature:
      type: string
      enum:
        [
          Breakfast,
          Air conditioning,
          Laptop friendly workspace,
          Baby seat,
          Washer,
          Towels,
          Fridge,
        ]

    createOffer:
      type: object
      required:
        - title
        - description
        - city
        - previewImage
        - propertyPhotos
        - premiumFlag
        - rating
        - propertyType
        - roomsNumber
        - guestsNumber
        - rentalCost
        - features
        - coordinates

      properties:
        title:
          type: string
          example: Charming Studio near central railway station

        description:
          type: string
          example: A cozy apartment located in the heart with stunning views of the Eiffel Tower. Perfect for couples and solo travelers
        publicationDate:
          type: string
          format: date-time

        city:
          $ref: '#/components/schemas/city'

        previewImage:
          type: string
          example: /images/paris-studio.jpg

        propertyPhotos:
          type: array
          items:
            type: string

        premiumFlag:
          type: boolean

        propertyType:
          $ref: '#/components/schemas/propertyType'

        roomsNumber:
          type: integer

        guestsNumber:
          type: integer

        rentalCost:
          type: number
        features:
          type: array
          items:
            $ref: '#/components/schemas/propertyFeature'
        coordinates:
          type: array
          minItems: 2
          maxItems: 2
          items:
            type: number

    updateOffer:
      type: object

      properties:
        title:
          type: string
          example: Charming Studio near central railway station

        description:
          type: string
          example: A cozy apartment located in the heart with stunning views of the Eiffel Tower. Perfect for couples and solo travelers
        publicationDate:
          type: string
          format: date-time

        city:
          $ref: '#/components/schemas/city'

        previewImage:
          type: string
          example: /images/paris-studio.jpg

        propertyPhotos:
          type: array
          items:
            type: string

        premiumFlag:
          type: boolean

        propertyType:
          $ref: '#/components/schemas/propertyType'

        roomsNumber:
          type: integer

        guestsNumber:
          type: integer

        rentalCost:
          type: number
        features:
          type: array
          items:
            $ref: '#/components/schemas/propertyFeature'
        coordinates:
          type: array
          minItems: 2
          maxItems: 2
          items:
            type: number

    offer:
      type: object
      properties:
        id:
          type: string
          example: 6329c3d6a04ab1061c6425ea

        title:
          type: string
          example: Charming Studio near central railway station

        description:
          type: string
          example: A cozy apartment located in the heart with stunning views of the Eiffel Tower. Perfect for couples and solo travelers
        publicationDate:
          type: string
          format: date-time

        city:
          $ref: '#/components/schemas/city'

        previewImage:
          type: string
          example: /images/paris-studio.jpg

        propertyPhotos:
          type: array
          items:
            type: string

        premiumFlag:
          type: boolean

        propertyType:
          $ref: '#/components/schemas/propertyType'

        roomsNumber:
          type: integer

        guestsNumber:
          type: integer

        rentalCost:
          type: number

        features:
          type: array
          items:
            $ref: '#/components/schemas/propertyFeature'

        coordinates:
          type: array
          minItems: 2
          maxItems: 2
          items:
            type: number

    userType:
      type: string
      enum: [pro, starter]

    createUser:
      type: object
      required:
        - email
        - name
        - password

      properties:
        email:
          type: string
          example: keks@htmlacademy.ru

        name:
          type: string
          example: Keks

        password:
          type: string
          example: 123456

        userType:
          $ref: '#/components/schemas/userType'

    createUserRDO:
      type: object
      properties:
        name:
          type: string
          example: Keks

        avatar:
          type: string

        userType:
          $ref: '#/components/schemas/userType'

    loggedUser:
      type: object
      properties:
        id:
          type: string
          example: 6329c3d6a04ab1061c6425ea
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR...

    user:
      type: object

      properties:
        id:
          type: string
          example: 6329c3d6a04ab1061c6425ea

        email:
          type: string
          example: keks@htmlacademy.ru

        userType:
          $ref: '#/components/schemas/userType'

        avatar:
          type: string
          format: uri
          example: /uploads/avatars/6329c3d6a04ab1061c6425ea.png

    comment:
      type: object
      properties:
        text:
          type: string
          example: 'looks nice'

        rating:
          type: number
          minimum: 1
          maximum: 5

    createComment:
      type: object
      required:
        - userId
        - offerId
        - text
        - rating

      properties:
        userId:
          type: string
          example: 6329c3d6a04ab1061c6425ea

        offerId:
          type: string
          example: 6329c3d6a04ab1061c6425ea

        text:
          type: string
          example: 'looks nice'

        rating:
          type: number
          example: 4

  parameters:
    offerId:
      name: offerId
      in: path
      required: true
      schema:
        type: string
        example: 6329c3d6a04ab1061c6425ea

    userId:
      name: userId
      in: path
      required: true
      schema:
        type: string
        example: 6329c3d6a04ab1061c6425ea
